#!/usr/bin/env bash
# Dump public.layer_styles from a PostgreSQL service and rewrite it as a
# portable layer_styles.sql (schema placeholder, no dump metadata).
#
# Typical use:
#   ./plugin/export_layer_styles.sh -o plugin/convert/processing/v2.0.2/layer_styles.sql \
#       5430_carttop1_en1_moleanos_porto_de_mos_20250603
#   ./plugin/export_layer_styles.sh -p 5434 -o layer_styles.sql <pg_service>

set -euo pipefail

usage() {
    echo "Usage: $0 [-o FILE] [-p PORT] <pg_service>" >&2
    echo "  -o FILE   Output SQL path (default: ./layer_styles.sql)" >&2
    echo "  -p PORT   PostgreSQL port (default: 5434)" >&2
    exit 1
}

output="./layer_styles.sql"
pg_port="5434"

while getopts ":o:p:h" opt; do
    case "$opt" in
        o) output="$OPTARG" ;;
        p) pg_port="$OPTARG" ;;
        h) usage ;;
        *) usage ;;
    esac
done
shift $((OPTIND - 1))

if [ -z "${1:-}" ]; then
    echo "Error: missing PostgreSQL service name." >&2
    usage
fi

service="$1"

if ! command -v pg_dump >/dev/null 2>&1; then
    echo "Error: pg_dump not found in PATH." >&2
    exit 1
fi

tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

dump="$tmpdir/layer_styles.new.sql"

pg_dump -p "$pg_port" "service=${service}" -t layer_styles --no-owner --no-privileges --attribute-inserts \
    > "$dump"

# Rewrite pg_dump output into the portable form used by the plugin.
# Schema statements are deleted through their terminating ';' so both older
# dumps (CREATE SEQUENCE + 2-line ALTER TABLE) and current dumps (multi-line
# ALTER TABLE ... GENERATED AS IDENTITY (...);) are stripped cleanly.
sed -i "s/VALUES ([0-9]\+, '[^']\+', '[^']\+', /VALUES ( current_database(), '{schema}', /g" "$dump"
sed -i "s/layer_styles (id,/layer_styles (/g" "$dump"
sed -i "s/owner, ui, update_time, //g" "$dump"
sed -i "s/'[a-z]\+', NULL, '202[^']\+', //g" "$dump"
sed -i '/^CREATE SEQUENCE/,/;/d' "$dump"
sed -i '/^ALTER SEQUENCE/,/;/d' "$dump"
sed -i '/^ALTER TABLE/,/;/d' "$dump"
sed -i '/^SELECT pg_catalog.setval/,/;/d' "$dump"
sed -E -i "s/CREATE TABLE/CREATE TABLE IF NOT EXISTS/g" "$dump"
sed -i "s/id integer NOT NULL,/id integer generated by default as identity NOT NULL PRIMARY KEY,/" "$dump"
sed -i '/CREATE TABLE/,+1000000!d' "$dump"
sed -i '/^--/d' "$dump"
sed -i '/\\restrict/d' "$dump"
sed -i '/\\unrestrict/d' "$dump"

mkdir -p "$(dirname "$output")"

if [ -f "$output" ]; then
    backup="${output%.sql}.old.sql"
    mv "$output" "$backup"
    echo "Existing file moved to $backup"
fi

mv "$dump" "$output"

echo "Wrote $output from service=${service} port=${pg_port}"
