#
# Esta script Python permite guardar os estilos de todos os layers na base de dados, a partir da consola do QGIS.
# Depois de guardados em base de dados, os comendos seguintes podem ser usados para gerar um ficheiro SQL com esses estilos.
# 
# Possíveis problemas e acertos:
# select * from public.layer_styles ls where type = 'Unknown geometry';
# select * from public.layer_styles ls where not useasdefault;
# select * from public.layer_styles ls where f_table_schema != 'public';
# delete from public.layer_styles ls where f_table_schema != 'public';
# update public.layer_styles set useasdefault = True where not useasdefault;
# update public.layer_styles set type = 'Point' where type = 'Unknown geometry';
#
# Save all layer styles to the database
# pg_dump service=portimao -t layer_styles --no-owner --no-privileges --attribute-inserts > layer_styles.new.sql

# sed -i "s/VALUES ([0-9]\+, '[^']\+', '[^']\+', /VALUES ( current_database(), '{schema}', /g" layer_styles.new.sql
# sed -i "s/layer_styles (id,/layer_styles (/g" layer_styles.new.sql
# sed -i "s/owner, ui, update_time, //g" layer_styles.new.sql
# sed -i "s/'[a-z]\+', NULL, '202[^']\+', //g" layer_styles.new.sql
# sed -E -i "s/CREATE (TABLE|SEQUENCE)/CREATE \1 IF NOT EXISTS/g" layer_styles.new.sql
# sed -i "/ALTER TABLE/,+1d" layer_styles.new.sql
# sed -i "/SELECT pg_catalog.setval/d" layer_styles.new.sql
# sed -i "/ALTER SEQUENCE/d" layer_styles.new.sql
# sed -i "/CREATE SEQUENCE/,+6d" layer_styles.new.sql
# sed -i "s/id integer NOT NULL,/id integer generated by default as identity NOT NULL PRIMARY KEY,/" layer_styles.new.sql   
# sed -i '/CREATE TABLE/,+1000000!d' layer_styles.new.sql
# sed -i '/^--/d' layer_styles.new.sql
# mv layer_styles.sql layer_styles.old.sql
# mv layer_styles.new.sql layer_styles.sql

mapGeometryType = {
    0: "Point",
    1: "Line",
    2: "Polygon",
    3: "UnknownGeometry",
    4: "NullGeometry",
}

layers = QgsProject.instance().mapLayers()

for layer in layers.values():
    if layer.type() == QgsMapLayer.VectorLayer:
        if mapGeometryType[layer.geometryType()] != "NullGeometry":
            print(layer.name())
            layer.deleteStyleFromDatabase
            layer.saveStyleToDatabase(name=layer.name(),description="Default style for {}".format(layer.name()), useAsDefault=True, uiFileContent="")